name: flutter_webview_pro
description: A Flutter plugin that provides a WebView widget who Support photo upload/take camera and Geolocation.
repository: https://github.com/wenzhiming/flutter-plugins/tree/dev/packages/webview_flutter/webview_flutter
issue_tracker: https://github.com/wenzhiming/flutter-plugins/issues
version: 3.0.4+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: webview_flutter_android
      ios:
        default_package: webview_flutter_wkwebview

dependencies:
  flutter:
    sdk: flutter
  webview_pro_android: ^2.8.3+3
  webview_pro_platform_interface: ^1.8.1+2 #^1.9.3+1
  webview_pro_wkwebview: ^2.7.1+3

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
